[workspace]
members = [
    "unic-langid",
    "unic-langid-impl",
    "unic-langid-macros",
    "unic-langid-macros-impl",
    "unic-locale",
    "unic-locale-impl",
    "unic-locale-macros",
    "unic-locale-macros-impl",
]
